### PR TITLE
allow version 2 from scheb/two-factor-bundle

### PR DESCRIPTION
**Pull request by ickbinhier**

### CODE REVIEW

**Comment by darookee** [comment]
Same as in #3, if it works with `2.0` I'd just replace the version requirement. Is it working for you?

**Comment by tubssp** [comment]
yes, I have tested with a private copy.

**Comment by binarious** [comment]
@darookee anything else needed for a merge?

**Comment by darookee** [comment]
@binarious No, I just didn't came around to it yet. Sorry for the delay...

**Comment by binarious** [comment]
@darookee No problem. Thank you for your work.

**Pull request merged**
