### PR TITLE
Add scheb 3.2 compatibility

### LINKED ISSUE #21: Scheb 3.2 compatibility
FYI: I'm working on making this bundle compatible with the new 3.2 release: https://github.com/scheb/two-factor-bundle/releases/tag/v3.2.0

This new version makes it possible to use multiple multi-factor authentication methods, so a user can choose between U2F or TOTP.

### PR DESCRIPTION
**Pull request by stephanvierkant**
I'm still working on it, but you can see the progress here.

Fixes #21

### CODE REVIEW

**Comment by scheb** [comment]
Would you publish a release? I'd like to merge scheb/two-factor-bundle#122

**Comment by stephanvierkant** [comment]
I think we're waiting for #26 (still Work In Progress, haven't had that much time last week), but since this bundle hasn't got a stable version yet in the first place, I'm OK with a new 0.x release.

ping @darookee

**Comment by darookee** [comment]
I just published 0.6.0.

**Comment by binarious** [comment]
This requires configuring scheb/two-factor-bundle, doesn't it? Just updated my application and the u2f login has gone away. Scheb before v3 doesn't need a configuration. We should add a hint in the readme, shouldn't we?

**Pull request merged**
