### PR TITLE
Symfony4 Compatibility

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/registertemplate/registerTemplate/
s/authcodeparameter/authCodeParameter/

### CODE REVIEW

**Comment by stephanvierkant** [comment]
ping @darookee

**Comment by darookee** [comment]
Well, this should not break anything... Thanks @PhilETaylor!

**Comment by PhilETaylor** [comment]
Its been so long since I opened this I cannot remember what it broke, but it certainly did raise some kind of error or message or I would not have taken the time to research it and debug it to the root issue.

Maybe I should have detailed that error - sorry about that, I was head deep in trying to get an app up and running in production again.

**Comment by darookee** [comment]
No Problem! :-)

**Comment by PhilETaylor** [comment]
I wanted to circle back and document why this change was needed. If you change the case back to all lower case you get this error:

Screenshot 2019-05-30 at 18 12 47

Because at the time the controller was:

Screenshot 2019-05-30 at 18 14 45

**Pull request merged**
